version: 2
jobs:
  test:
    docker:
      - image: circleci/python:3.6.1
    working_directory: ~/repo/tests
    steps:
      - checkout:
          path: ~/repo

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "test-requirements.txt" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r test-requirements.txt

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "test-requirements.txt" }}
      
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            pytest

          
workflows:
  version: 2
  test_deploy:
    jobs:
      - test
