version: 2
jobs:
  test:
    docker:
      - image: circleci/python:3.6.1
    environment:
      AWS_DEFAULT_REGION=us-west-2
    working_directory: ~/repo
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "tests/test-requirements.txt" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r tests/test-requirements.txt

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "tests/test-requirements.txt" }}
      
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            python -m pytest tests
  deploy:
    docker:
      - image: circleci/node:8.10

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: Install Serverless CLI and dependencies
          command: |
            sudo npm i -g serverless
            npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-
        
      - run:
          name: Deploy application to dev
          command: sls deploy --verbose --stage dev --region us-west-2
          
workflows:
  version: 2
  test_deploy:
    jobs:
      - test
      - deploy:
          requires:
            - test

